# Generated by Django 3.2.9 on 2021-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0002_auto_20211116_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='pathogen',
            field=models.CharField(help_text='Pathogen', max_length=20, null=True),
        ),
    ]
