# Generated by Django 3.2.9 on 2021-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_alter_disease_pathogen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='pathogen',
            field=models.CharField(blank=True, help_text='Pathogen', max_length=20, null=True),
        ),
    ]
