# Generated by Django 3.2.9 on 2021-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0005_auto_20211118_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='salary',
            field=models.PositiveIntegerField(blank=True, help_text='Annual salary', null=True),
        ),
    ]
