# Generated by Django 3.2.9 on 2021-11-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0006_alter_myuser_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('doctor_access', 'Can interact with diseases, disease types and discoveries')]},
        ),
        migrations.AlterModelOptions(
            name='publicservant',
            options={'permissions': [('servant_access', 'Can interact with records and discoveries')]},
        ),
    ]
