# Generated by Django 3.2.9 on 2021-11-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0008_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicservant',
            options={'permissions': [('servant_access', 'servant_access')]},
        ),
    ]
