# Generated by Django 3.2.9 on 2021-11-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0009_alter_publicservant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialize',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
