# Generated by Django 3.2.9 on 2021-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0010_auto_20211118_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disease',
            name='pathogen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='description',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='publicservant',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_death',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_patients',
            field=models.PositiveIntegerField(),
        ),
    ]
