# Generated by Django 3.2.9 on 2021-11-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0011_auto_20211118_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='diseasetype',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
