# Generated by Django 3.2.9 on 2021-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0012_auto_20211118_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discover',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialize',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
